//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backgammon.Client.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class backgammonEntities : DbContext
    {
        public backgammonEntities()
            : base("name=backgammonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AvailableState> AvailableStates { get; set; }
        public virtual DbSet<Avatar> Avatars { get; set; }
        public virtual DbSet<FriendRequest> FriendRequests { get; set; }
        public virtual DbSet<FriendShip> FriendShips { get; set; }
        public virtual DbSet<Lobby> Lobbies { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Participate> Participates { get; set; }
        public virtual DbSet<Play> Plays { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<SocialMedia> SocialMedias { get; set; }
        public virtual DbSet<StateLobby> StateLobbies { get; set; }
        public virtual DbSet<TypeSocialMedia> TypeSocialMedias { get; set; }
    }
}
