//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backgammon.Client.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BackgammonEntities : DbContext
    {
        public BackgammonEntities()
            : base("name=BackgammonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AvailableState> AvailableStates { get; set; }
        public virtual DbSet<Avatar> Avatars { get; set; }
        public virtual DbSet<FriendRequest> FriendRequests { get; set; }
        public virtual DbSet<FriendShip> FriendShips { get; set; }
        public virtual DbSet<Lobby> Lobbies { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Participate> Participates { get; set; }
        public virtual DbSet<Play> Plays { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<SocialMedia> SocialMedias { get; set; }
        public virtual DbSet<StateLobby> StateLobbies { get; set; }
        public virtual DbSet<TypeSocialMedia> TypeSocialMedias { get; set; }
    }
}
