//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backgammon.Client.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Participate
    {
        public int IdLobbyFK { get; set; }
        public int PlayerOneFK { get; set; }
        public int PlayerTwoFK { get; set; }
        public int IdParticipatePK { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Lobby Lobby { get; set; }
    }
}
