//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backgammon.Client.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.Accounts = new ObservableCollection<Account>();
            this.SocialMedias = new ObservableCollection<SocialMedia>();
        }
    
        public int Wins { get; set; }
        public int IdAvatarFK { get; set; }
        public string Username { get; set; }
        public int Points { get; set; }
        public int IdAvailableStateFK { get; set; }
        public string Description { get; set; }
        public int IdProfilePK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Account> Accounts { get; set; }
        public virtual AvailableState AvailableState { get; set; }
        public virtual Avatar Avatar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<SocialMedia> SocialMedias { get; set; }
    }
}
