//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backgammon.Client.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public string link { get; set; }
        public int idProfileFK { get; set; }
        public int idTypeSocialMediaFK { get; set; }
        public int idSocialMediaPK { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual TypeSocialMedia TypeSocialMedia { get; set; }
    }
}
