//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backgammon.Client.Data
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class SocialMedia
    {
        public string Link { get; set; }
        public int IdProfileFK { get; set; }
        public int IdTypeSocialMediaFK { get; set; }
        public int IdSocialMediaPK { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual TypeSocialMedia TypeSocialMedia { get; set; }
    }
}
